// PM2 生态系统配置文件
// 使用方式: pm2 start deploy/scripts/pm2.ecosystem.config.js

module.exports = {
  apps: [
    {
      name: 'redpacket-bot',
      script: 'app.py',
      interpreter: 'python',
      cwd: '/app',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/bot-error.log',
      out_file: './logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'redpacket-web-admin',
      script: 'uvicorn',
      args: 'web_admin.main:app --host 0.0.0.0 --port 8000 --workers 2',
      interpreter: 'python',
      cwd: '/app',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/web-admin-error.log',
      out_file: './logs/web-admin-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'redpacket-miniapp-api',
      script: 'uvicorn',
      args: 'miniapp.main:app --host 0.0.0.0 --port 8080 --workers 2',
      interpreter: 'python',
      cwd: '/app',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: './logs/miniapp-api-error.log',
      out_file: './logs/miniapp-api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'redpacket-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/app/frontend-next',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: './logs/frontend-error.log',
      out_file: './logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
  ],
};

